baseURL = 'https://ss44.ca/'
locale = 'en-ca'
title = 'Shajinder Singh Padda'
theme = "hugo-theme-nightfall"

[menu]
#  [[menu.header]]
#    name = "notes"
#    weight = 0
#    url = "notes"

#  [[menu.header]]
#    name = "resume"
#    weight = 2
#    url = "resume.pdf"

[params]
user = "shajinder"
hostname = "ss44.ca"
rotating_titles = [
  "oh, hi.",
  "hello there.",
  "greetings.",
  "eh, yo."
  "ola",
]
rotating_titles_duration = 5

[[params.social]]
key = 0
name = "github"
url = "https://github.com/ss44"
target = "_blank"
aria = "GitHub Profile"
icon = "fa-brands fa-github"



[[params.social]]
key = 2
name = "linkedIn"
url = "https://www.linkedin.com/in/shajinder-singh-padda-012a7739"
aria = "LinkedIn Profile"
icon = "fa-brands fa-linkedin"
