baseURL = 'https://ss44.ca/'
locale = 'en-ca'
title = 'Shajinder Singh Padda'
theme = "hugo-theme-nightfall"
ignoreFiles = ["cobalt-cv", "cobalt\\.cv"]

[menu]
#  [[menu.header]]
#    name = "notes"
#    weight = 0
#    url = "notes"

  [[menu.header]]
    name = "resume.html"
    weight = 2
    url = "resume"
    pre = "fa-solid fa-file-code"

  [[menu.header]]
    name = "resume.pdf"
    weight = 3
    url = "resume.pdf"
    pre = "fa-solid fa-file-pdf"

[params]
description = "Senior Systems Architect and Full Stack Developer with 20+ years of experience."
images = ["/meta-preview.png"]
user = "shajinder"
hostname = "ss44.ca"
rotating_titles = [
  "oh, hi.",
  "hello there.",
  "greetings.",
  "eh, yo!",
  "ola!"
]
rotating_titles_duration = 5

[[params.social]]
key = 0
name = "github"
url = "https://github.com/ss44"
target = "_blank"
aria = "GitHub Profile"
icon = "fa-brands fa-github"



[[params.social]]
key = 2
name = "linkedIn"
url = "https://www.linkedin.com/in/ss44"
aria = "LinkedIn Profile"
icon = "fa-brands fa-linkedin"
